### PR TITLE
LP-293 Name ending nested radio buttons

### PR DESCRIPTION
**Pull request by markpit**
### JIRA link
https://companieshouse.atlassian.net/browse/LP-293

### Change description
Draft - Try to find a way to stop the welsh buttons being hidden on selection.
Splitting the radio buttons so they have separate 'name' values on the form seems to stop them being hidden.
Then made 'name_ending' field a hidden field that is populated by javascript on button click.
Seems to work on submitting but might need more javascript to populate the correct button when resuming a journey or populating page from stored data.

### Work checklist

- [ ] Tests added where applicable
- [ ] UI changes look good on mobile
- [ ] UI changes meet accessibility criteria

### Merge instructions

We are committed to keeping commit history clean, consistent and linear. To achieve this commit should be structured as follows:

```
<type>[optional scope]: <description>
```

and contain the following structural elements:

- fix: a commit that patches a bug in your codebase (this correlates with PATCH in semantic versioning),
- feat: a commit that introduces a new feature to the codebase (this correlates with MINOR in semantic versioning),
- BREAKING CHANGE: a commit that has a footer `BREAKING CHANGE:` introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of any type,
- types other than `fix:` and `feat:` are allowed, for example `build:`, `chore:`, `ci:`, `docs:`, `style:`, `refactor:`, `perf:`, `test:`, and others,
- footers other than `BREAKING CHANGE: <description>` may be provided.

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Comment by ch-code-analysis** [comment]
CI: No security warnings found

**Review by mwestacott — COMMENTED** [review]
LGTM not too complex

**Comment by markpit** [comment]
closing this now as the UX team have agreed not to have nested radio buttons.

**Pull request closed without merging**
